# Generated by Django 6.0.2 on 2026-02-15 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hire.service')),
            ],
        ),
    ]
